=== MarcosManteca017/ProcesamientoDeLaInformacionEnAplicacionesTelematicas/P1/Fase2/Robot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                        targetNamespace="http://www.piat.upm.es/robot" 
                        xmlns:tns="http://www.piat.upm.es/robot" 
                        elementFormDefault="qualified"> 

<xsd:element name="robot" type="tns:tipoRobot"/>
<xsd:complexType name="tipoRobot">
    <xsd:sequence>
        <xsd:element name="funcionalidad" type="xsd:string"/>
        <xsd:element name="sistemaLimpieza" type="xsd:string"/>
        <xsd:element name="homologaciones" type="tns:tipoHomologaciones" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="sensores" type="tns:tipoSensores" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="actuadores" type="tns:tipoActuadores" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
<xsd:attribute name="idRobot" type="tns:tipoIdRobot"/>
</xsd:complexType>
<xsd:simpleType name="tipoIdRobot">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="id-[0-9]{3}"/>
    </xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="tipoHomologaciones"> <!-- restriction lista de 0-10 valores token -->
    <xsd:restriction base="tns:tipoLista">
        <xsd:minLength value="1"/>
        <xsd:maxLength value="10"/>
    </xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="tipoLista">
    <xsd:list>
        <xsd:simpleType>
            <xsd:restriction base="xsd:token"/>
        </xsd:simpleType>
    </xsd:list>
</xsd:simpleType>
<xsd:complexType name="tipoSensores">
    <xsd:sequence>
        <xsd:element name="numeroSensores" type="xsd:int"/>
        <xsd:element name="sensor" type="tns:tipoSensor" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>
<xsd:complexType name="tipoSensor">
    <xsd:sequence>
        <xsd:element name="patogeno" type="xsd:string"/>
        <xsd:element name="densidad" type="tns:tipoDensidad"/>
    </xsd:sequence>
    <xsd:attribute name="idSensor" type="tns:tipoIdSensor"/>
</xsd:complexType>
<xsd:simpleType name="tipoIdSensor">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="[a-z]{2}[0-9]{1}[A-Z]{2}"/>
    </xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="tipoDensidad">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="[0-9]{4}[a-z]{6}"/>
    </xsd:restriction>
</xsd:simpleType>
<xsd:complexType name="tipoActuadores">
    <xsd:sequence>
        <xsd:element name="numeroActuadores" type="xsd:int"/>
        <xsd:element name="actuador" type="tns:tipoActuador" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>
<xsd:complexType name="tipoActuador">
    <xsd:sequence>
        <xsd:element name="descripcion" type="xsd:string"/>
        <xsd:element name="alcanceSituacion" type="tns:tipoAlcance"/>
    </xsd:sequence>
<xsd:attribute name="idActuador" type="tns:tipoIdActuador"/>
</xsd:complexType>
<xsd:simpleType name="tipoIdActuador">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="[A-Z]{2}[0-9]{2}"/>
    </xsd:restriction>
</xsd:simpleType>
<xsd:complexType name="tipoAlcance">
    <xsd:sequence>
        <xsd:element name="tipoActuacion" type="xsd:string"/>
        <xsd:element name="fechasActuacion" type="tns:tipoFechas" minOccurs="1" maxOccurs="10"/>
    </xsd:sequence>

</xsd:complexType>
<xsd:simpleType name="tipoFechas"> <!-- nose hacerlo-->
    <xsd:list>
        <xsd:simpleType>
            <xsd:restriction base="tns:tipoListaFechas"/>
        </xsd:simpleType>
    </xsd:list>
</xsd:simpleType>
<xsd:simpleType name="tipoListaFechas">
    <xsd:union memberTypes="xsd:time xsd:dateTime"/>
</xsd:simpleType>
</xsd:schema>

=== MarcosManteca017/ProcesamientoDeLaInformacionEnAplicacionesTelematicas/P1/Fase2/Robot2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rob:robot idRobot="id-252" xmlns:xi="http://www.w3.org/2001/XInclude"
xmlns:rob="http://www.piat.upm.es/robot" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.piat.upm.es/robot Robot.xsd">
    <rob:funcionalidad>Limpieza con vapor de cristales</rob:funcionalidad>
    <rob:sistemaLimpieza>vapor</rob:sistemaLimpieza>
    <rob:homologaciones>dise√±o color ruedas </rob:homologaciones>
    <rob:sensores>
        <rob:numeroSensores>5</rob:numeroSensores>
        <rob:sensor idSensor="ox2AV">
            <rob:patogeno>estafilococo</rob:patogeno>
            <rob:densidad>3000metros</rob:densidad>
        </rob:sensor>
    </rob:sensores>
    <rob:actuadores>
        <rob:numeroActuadores>5</rob:numeroActuadores>
        <rob:actuador idActuador="AC01">
            <rob:descripcion>Actua con una limpieza diaria</rob:descripcion>
            <rob:alcanceSituacion>
                <rob:tipoActuacion>Limpieza diaria</rob:tipoActuacion>
                <rob:fechasActuacion>10:30:00 12:30:00</rob:fechasActuacion>
            </rob:alcanceSituacion>
        </rob:actuador>
        <rob:actuador idActuador="AD02">
            <rob:descripcion>Actua con una limpieza trimestral</rob:descripcion>
            <rob:alcanceSituacion>
                <rob:tipoActuacion>Limpieza trimestral</rob:tipoActuacion>
                <rob:fechasActuacion>14:30:00 22:15:00</rob:fechasActuacion>
            </rob:alcanceSituacion>
        </rob:actuador>
    </rob:actuadores>
</rob:robot>

=== MarcosManteca017/ProcesamientoDeLaInformacionEnAplicacionesTelematicas/P1/Fase2/Robot1.xml
<?xml version="1.0" encoding="UTF-8"?>
<rob:robot idRobot="id-251" xmlns:xi="http://www.w3.org/2001/XInclude"
 xmlns:rob="http://www.piat.upm.es/robot" 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.piat.upm.es/robot Robot.xsd">
    <rob:funcionalidad>Limpiza con ozono</rob:funcionalidad>
    <rob:sistemaLimpieza>ozono</rob:sistemaLimpieza>
    <rob:homologaciones>dise√±o pintura cableado</rob:homologaciones>
    <rob:sensores>
        <rob:numeroSensores>8</rob:numeroSensores>
        <rob:sensor idSensor="ox1AV">
            <rob:patogeno>estafilococo</rob:patogeno>
            <rob:densidad>5000metros</rob:densidad>
        </rob:sensor>
        <rob:sensor idSensor="ox2AV">
            <rob:patogeno>Gripe</rob:patogeno>
            <rob:densidad>6000metros</rob:densidad>
        </rob:sensor>
    </rob:sensores>
    <rob:actuadores>
        <rob:numeroActuadores>5</rob:numeroActuadores>
        <rob:actuador idActuador="AC01">
            <rob:descripcion>Limpieza con ozono de zonas comunes</rob:descripcion>
            <rob:alcanceSituacion>
                <rob:tipoActuacion>Limpieza diaria</rob:tipoActuacion>
                <rob:fechasActuacion>13:15:00</rob:fechasActuacion>
                <rob:fechasActuacion>18:20:00</rob:fechasActuacion>
            </rob:alcanceSituacion>
        </rob:actuador>
    </rob:actuadores>
</rob:robot>
